version: '3.8'

services:
  ppt-hyperlink-converter:
    build: .
    container_name: ppt_hyperlink_api
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - /tmp:/tmp  # Mount temp directory for processing
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s